export const GET_COUNTRIES = 'GET_COUNTRIES';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';
